"""fix base and fk

Revision ID: 3426de3d4e46
Revises: eda50a4d0553
Create Date: 2026-01-03 17:53:58.075752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3426de3d4e46'
down_revision: Union[str, Sequence[str], None] = 'eda50a4d0553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_password_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('signer',
    sa.Column('signer_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('national_id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=True),
    sa.Column('photo_id_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('signer_id')
    )
    op.create_index(op.f('ix_signer_national_id'), 'signer', ['national_id'], unique=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('face_embedding', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('user_account', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('user_account_email_idx'), 'user_account', ['email'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('user_account', 'password_hash',
               existing_type=sa.String(),
               type_=sa.CHAR(length=60),
               existing_nullable=True)
    op.alter_column('user_account', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('user_account_user_id_seq'::regclass)"))
    op.create_foreign_key(op.f('document_company_id_fkey'), 'document', 'company', ['company_id'], ['company_id'], ondelete='CASCADE')
    op.alter_column('document', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('document', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('document', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('document', 'hash_sha256',
               existing_type=sa.String(),
               type_=sa.CHAR(length=64),
               existing_nullable=False)
    op.alter_column('document', 'company_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('document', 'document_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('document', 'status_id')
    op.drop_column('document', 'file_path')
    op.drop_column('document', 'file_name')
    op.create_table('witness',
    sa.Column('witness_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('element_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('state_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('witness_value_hex', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('validated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['accumulator_element.element_id'], name=op.f('witness_element_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['accumulator_state.state_id'], name=op.f('witness_state_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('witness_id', name=op.f('witness_pkey')),
    sa.UniqueConstraint('element_id', name=op.f('witness_element_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('identity_document',
    sa.Column('identity_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('signer_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.CHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('validation_status', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('identity_id', name=op.f('identity_document_pkey'))
    )
    op.create_table('document_signer',
    sa.Column('doc_sign_id', sa.BIGINT(), server_default=sa.text("nextval('document_signer_doc_sign_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('signer_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sign_order', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('authenticated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('signed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], name='document_signer_document_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['document_status.status_id'], name='document_signer_status_id_fkey'),
    sa.PrimaryKeyConstraint('doc_sign_id', name='document_signer_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('auth_log',
    sa.Column('log_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('mfa_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('logged_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('log_id', name=op.f('auth_log_pkey'))
    )
    op.create_table('accumulator_state',
    sa.Column('state_id', sa.BIGINT(), server_default=sa.text("nextval('accumulator_state_state_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('previous_state_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('state_value_hex', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('generator_hex', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('modulus_n_hex', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['previous_state_id'], ['accumulator_state.state_id'], name='accumulator_state_previous_state_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('state_id', name='accumulator_state_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('document_status',
    sa.Column('status_id', sa.INTEGER(), server_default=sa.text("nextval('document_status_status_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('status_id', name='document_status_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('digital_signature',
    sa.Column('signature_id', sa.BIGINT(), server_default=sa.text("nextval('digital_signature_signature_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('doc_sign_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('signer_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('signature_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('signed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doc_sign_id'], ['document_signer.doc_sign_id'], name='digital_signature_doc_sign_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('signature_id', name='digital_signature_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('otp_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('otp_codes_pkey')),
    sa.UniqueConstraint('email', name=op.f('otp_codes_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('accumulator_element',
    sa.Column('element_id', sa.BIGINT(), server_default=sa.text("nextval('accumulator_element_element_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('signature_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('hash_hex', sa.CHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('x_value_hex', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], name='accumulator_element_document_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signature_id'], ['digital_signature.signature_id'], name='accumulator_element_signature_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('element_id', name='accumulator_element_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_accumulator_hash'), 'accumulator_element', ['hash_hex'], unique=False)
    op.create_table('company',
    sa.Column('company_id', sa.BIGINT(), server_default=sa.text("nextval('company_company_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('legal_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tax_id', sa.CHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], name='company_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', name='company_pkey'),
    sa.UniqueConstraint('tax_id', name='company_tax_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('public_accumulator_registry',
    sa.Column('registry_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('state_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), server_default=sa.text("'internal'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['accumulator_state.state_id'], name=op.f('public_accumulator_registry_state_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('registry_id', name=op.f('public_accumulator_registry_pkey')),
    sa.UniqueConstraint('state_id', name=op.f('public_accumulator_registry_state_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('audit_log',
    sa.Column('audit_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('entity_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('audit_log_pkey'))
    )
    op.create_index(op.f('idx_audit_entity'), 'audit_log', ['entity_name', 'entity_id'], unique=False)
    op.create_table('accumulator_element_state',
    sa.Column('element_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('state_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['accumulator_element.element_id'], name=op.f('accumulator_element_state_element_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['accumulator_state.state_id'], name=op.f('accumulator_element_state_state_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('element_id', name=op.f('accumulator_element_state_pkey')),
    sa.UniqueConstraint('element_id', 'state_id', name=op.f('accumulator_element_state_element_id_state_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_signer_national_id'), table_name='signer')
    op.drop_table('signer')
    op.drop_table('reset_password_tokens')
    # ### end Alembic commands ###
