"""sync_all_models_to_db

Revision ID: 4c9409a6395a
Revises: a7c4d8e91f23
Create Date: 2026-05-26 20:51:19.630511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c9409a6395a'
down_revision: Union[str, Sequence[str], None] = 'a7c4d8e91f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accumulator_element', 'element_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('accumulator_element', 'document_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('accumulator_element', 'signature_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('accumulator_element', 'hash_hex',
               existing_type=sa.CHAR(length=64),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('accumulator_element', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('idx_accumulator_hash'), table_name='accumulator_element')
    op.drop_constraint(op.f('accumulator_element_document_id_fkey'), 'accumulator_element', type_='foreignkey')
    op.drop_constraint(op.f('accumulator_element_signature_id_fkey'), 'accumulator_element', type_='foreignkey')
    op.create_foreign_key(None, 'accumulator_element', 'document', ['document_id'], ['document_id'])
    op.create_foreign_key(None, 'accumulator_element', 'digital_signature', ['signature_id'], ['signature_id'])
    op.alter_column('accumulator_element_state', 'element_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('accumulator_element_state', 'state_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint(op.f('accumulator_element_state_element_id_state_id_key'), 'accumulator_element_state', type_='unique')
    op.drop_constraint(op.f('accumulator_element_state_element_id_fkey'), 'accumulator_element_state', type_='foreignkey')
    op.drop_constraint(op.f('accumulator_element_state_state_id_fkey'), 'accumulator_element_state', type_='foreignkey')
    op.create_foreign_key(None, 'accumulator_element_state', 'accumulator_element', ['element_id'], ['element_id'])
    op.create_foreign_key(None, 'accumulator_element_state', 'accumulator_state', ['state_id'], ['state_id'])
    op.alter_column('accumulator_state', 'state_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('accumulator_state', 'previous_state_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('accumulator_state', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint(op.f('accumulator_state_previous_state_id_fkey'), 'accumulator_state', type_='foreignkey')
    op.create_foreign_key(None, 'accumulator_state', 'accumulator_state', ['previous_state_id'], ['state_id'])
    op.alter_column('audit_log', 'audit_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('audit_log', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('audit_log', 'entity_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('idx_audit_entity'), table_name='audit_log')
    op.alter_column('company', 'company_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('company', 'tax_id',
               existing_type=sa.CHAR(length=14),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('company', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('company', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('company', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('company', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'company', ['user_id'])
    op.drop_constraint(op.f('company_user_id_fkey'), 'company', type_='foreignkey')
    op.create_foreign_key(None, 'company', 'user_account', ['user_id'], ['user_id'])
    op.alter_column('digital_signature', 'signature_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('digital_signature', 'doc_sign_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('digital_signature', 'signer_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('digital_signature_validation_code_idx'), table_name='digital_signature', postgresql_where='(validation_code IS NOT NULL)')
    op.alter_column('document', 'document_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('document', 'company_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('document', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('document', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('document', 'hash_sha256',
               existing_type=sa.CHAR(length=64),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('document', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('document', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('document', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('document', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('document_company_id_fkey'), 'document', type_='foreignkey')
    op.drop_constraint(op.f('fk_document_signer_signer'), 'document_signer', type_='foreignkey')
    op.drop_constraint(op.f('fk_document_signer_document'), 'document_signer', type_='foreignkey')
    op.create_foreign_key(None, 'document_signer', 'document', ['document_id'], ['document_id'])
    op.create_foreign_key(None, 'document_signer', 'signer', ['signer_id'], ['signer_id'])
    op.drop_constraint(op.f('document_status_name_key'), 'document_status', type_='unique')
    op.alter_column('public_accumulator_registry', 'registry_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('public_accumulator_registry', 'state_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint(op.f('public_accumulator_registry_state_id_key'), 'public_accumulator_registry', type_='unique')
    op.drop_constraint(op.f('public_accumulator_registry_state_id_fkey'), 'public_accumulator_registry', type_='foreignkey')
    op.create_foreign_key(None, 'public_accumulator_registry', 'accumulator_state', ['state_id'], ['state_id'])
    op.alter_column('user_account', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_account', 'password_hash',
               existing_type=sa.CHAR(length=60),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('user_account_email_idx'), table_name='user_account', postgresql_where='(deleted_at IS NULL)')
    op.drop_column('user_account', 'face_embedding')
    op.alter_column('witness', 'witness_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('witness', 'element_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('witness', 'state_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('witness', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('idx_witness_element_state'), table_name='witness')
    op.drop_constraint(op.f('witness_state_id_fkey'), 'witness', type_='foreignkey')
    op.drop_constraint(op.f('witness_element_id_fkey'), 'witness', type_='foreignkey')
    op.create_foreign_key(None, 'witness', 'accumulator_state', ['state_id'], ['state_id'])
    op.create_foreign_key(None, 'witness', 'accumulator_element', ['element_id'], ['element_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'witness', type_='foreignkey')
    op.drop_constraint(None, 'witness', type_='foreignkey')
    op.create_foreign_key(op.f('witness_element_id_fkey'), 'witness', 'accumulator_element', ['element_id'], ['element_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('witness_state_id_fkey'), 'witness', 'accumulator_state', ['state_id'], ['state_id'], ondelete='CASCADE')
    op.create_index(op.f('idx_witness_element_state'), 'witness', ['element_id', 'state_id'], unique=False)
    op.alter_column('witness', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('witness', 'state_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('witness', 'element_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('witness', 'witness_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('user_account', sa.Column('face_embedding', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.create_index(op.f('user_account_email_idx'), 'user_account', ['email'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('user_account', 'password_hash',
               existing_type=sa.String(),
               type_=sa.CHAR(length=60),
               existing_nullable=True)
    op.alter_column('user_account', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'public_accumulator_registry', type_='foreignkey')
    op.create_foreign_key(op.f('public_accumulator_registry_state_id_fkey'), 'public_accumulator_registry', 'accumulator_state', ['state_id'], ['state_id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('public_accumulator_registry_state_id_key'), 'public_accumulator_registry', ['state_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('public_accumulator_registry', 'state_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('public_accumulator_registry', 'registry_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_unique_constraint(op.f('document_status_name_key'), 'document_status', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'document_signer', type_='foreignkey')
    op.drop_constraint(None, 'document_signer', type_='foreignkey')
    op.create_foreign_key(op.f('fk_document_signer_document'), 'document_signer', 'document', ['document_id'], ['document_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_document_signer_signer'), 'document_signer', 'signer', ['signer_id'], ['signer_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('document_company_id_fkey'), 'document', 'company', ['company_id'], ['company_id'], ondelete='CASCADE')
    op.alter_column('document', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('document', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('document', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('document', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('document', 'hash_sha256',
               existing_type=sa.String(),
               type_=sa.CHAR(length=64),
               existing_nullable=False)
    op.alter_column('document', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('document', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('document', 'company_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('document', 'document_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('digital_signature_validation_code_idx'), 'digital_signature', ['validation_code'], unique=True, postgresql_where='(validation_code IS NOT NULL)')
    op.alter_column('digital_signature', 'signer_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('digital_signature', 'doc_sign_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('digital_signature', 'signature_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.create_foreign_key(op.f('company_user_id_fkey'), 'company', 'user_account', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'company', type_='unique')
    op.alter_column('company', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('company', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('company', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('company', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('company', 'tax_id',
               existing_type=sa.String(),
               type_=sa.CHAR(length=14),
               existing_nullable=False)
    op.alter_column('company', 'company_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('idx_audit_entity'), 'audit_log', ['entity_name', 'entity_id'], unique=False)
    op.alter_column('audit_log', 'entity_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('audit_log', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('audit_log', 'audit_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'accumulator_state', type_='foreignkey')
    op.create_foreign_key(op.f('accumulator_state_previous_state_id_fkey'), 'accumulator_state', 'accumulator_state', ['previous_state_id'], ['state_id'], ondelete='SET NULL')
    op.alter_column('accumulator_state', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('accumulator_state', 'previous_state_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('accumulator_state', 'state_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'accumulator_element_state', type_='foreignkey')
    op.drop_constraint(None, 'accumulator_element_state', type_='foreignkey')
    op.create_foreign_key(op.f('accumulator_element_state_state_id_fkey'), 'accumulator_element_state', 'accumulator_state', ['state_id'], ['state_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('accumulator_element_state_element_id_fkey'), 'accumulator_element_state', 'accumulator_element', ['element_id'], ['element_id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('accumulator_element_state_element_id_state_id_key'), 'accumulator_element_state', ['element_id', 'state_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('accumulator_element_state', 'state_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('accumulator_element_state', 'element_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(None, 'accumulator_element', type_='foreignkey')
    op.drop_constraint(None, 'accumulator_element', type_='foreignkey')
    op.create_foreign_key(op.f('accumulator_element_signature_id_fkey'), 'accumulator_element', 'digital_signature', ['signature_id'], ['signature_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('accumulator_element_document_id_fkey'), 'accumulator_element', 'document', ['document_id'], ['document_id'], ondelete='CASCADE')
    op.create_index(op.f('idx_accumulator_hash'), 'accumulator_element', ['hash_hex'], unique=False)
    op.alter_column('accumulator_element', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('accumulator_element', 'hash_hex',
               existing_type=sa.String(length=64),
               type_=sa.CHAR(length=64),
               existing_nullable=False)
    op.alter_column('accumulator_element', 'signature_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('accumulator_element', 'document_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('accumulator_element', 'element_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
