"""add_public_key_pem_to_digital_signature

Revision ID: 70e4e9058181
Revises: 8b3c22fe2832
Create Date: 2026-05-26 23:47:37.124332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e4e9058181'
down_revision: Union[str, Sequence[str], None] = '8b3c22fe2832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_signature', sa.Column('public_key_pem', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digital_signature', 'public_key_pem')
    # ### end Alembic commands ###
