"""add_attempts_to_otp_codes

Revision ID: 9fbf851ebf0d
Revises: 4c9409a6395a
Create Date: 2026-05-26 22:06:50.117484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbf851ebf0d'
down_revision: Union[str, Sequence[str], None] = '4c9409a6395a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_codes', 'attempts')
    # ### end Alembic commands ###
