"""add per-document biometric to document_signer

Revision ID: de4b23285cad
Revises: e72854956915
Create Date: 2026-06-27 23:34:50.998196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de4b23285cad'
down_revision: Union[str, Sequence[str], None] = 'e72854956915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_signer', sa.Column('photo_id_url', sa.String(), nullable=True))
    op.add_column('document_signer', sa.Column('face_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_signer', 'face_embedding')
    op.drop_column('document_signer', 'photo_id_url')
    # ### end Alembic commands ###
