"""initial schema

Revision ID: e72854956915
Revises: 
Create Date: 2026-06-27 18:40:46.162270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e72854956915'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accumulator_state',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('previous_state_id', sa.Integer(), nullable=True),
    sa.Column('state_value_hex', sa.Text(), nullable=False),
    sa.Column('generator_hex', sa.Text(), nullable=False),
    sa.Column('modulus_n_hex', sa.Text(), nullable=False),
    sa.Column('base_counter', sa.Integer(), nullable=True),
    sa.Column('record_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['previous_state_id'], ['accumulator_state.state_id'], ),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('audit_log',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('auth_log',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('mfa_type', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='1', nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('digital_signature',
    sa.Column('signature_id', sa.Integer(), nullable=False),
    sa.Column('doc_sign_id', sa.Integer(), nullable=False),
    sa.Column('signer_id', sa.Integer(), nullable=False),
    sa.Column('signature_data', sa.Text(), nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('validation_code', sa.String(length=64), nullable=True),
    sa.Column('validation_url', sa.Text(), nullable=True),
    sa.Column('signed_file_path', sa.Text(), nullable=True),
    sa.Column('signed_file_sha256', sa.String(length=64), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('signature_id')
    )
    op.create_table('document',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('hash_sha256', sa.String(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('document_status',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_table('identity_document',
    sa.Column('identity_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('signer_id', sa.BigInteger(), nullable=False),
    sa.Column('document_type', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('file_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('validation_status', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('identity_id')
    )
    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('signer_status',
    sa.Column('status_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_account',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accumulator_element',
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('signature_id', sa.Integer(), nullable=True),
    sa.Column('hash_hex', sa.String(length=64), nullable=False),
    sa.Column('x_value_hex', sa.Text(), nullable=False),
    sa.Column('x_nonce', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], ),
    sa.ForeignKeyConstraint(['signature_id'], ['digital_signature.signature_id'], ),
    sa.PrimaryKeyConstraint('element_id')
    )
    op.create_table('company',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('tax_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('tax_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notification_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('public_accumulator_registry',
    sa.Column('registry_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['accumulator_state.state_id'], ),
    sa.PrimaryKeyConstraint('registry_id')
    )
    op.create_table('reset_password_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('signer',
    sa.Column('signer_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('national_id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=True),
    sa.Column('photo_id_url', sa.String(), nullable=True),
    sa.Column('face_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('signer_id')
    )
    op.create_index(op.f('ix_signer_national_id'), 'signer', ['national_id'], unique=False)
    op.create_table('accumulator_element_state',
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['accumulator_element.element_id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['accumulator_state.state_id'], ),
    sa.PrimaryKeyConstraint('element_id')
    )
    op.create_table('document_signer',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('signer_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('face_match_score', sa.Float(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], ),
    sa.ForeignKeyConstraint(['signer_id'], ['signer.signer_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['signer_status.status_id'], ),
    sa.PrimaryKeyConstraint('document_id', 'signer_id')
    )
    op.create_table('signer_key_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('signer_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('revoked_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['signer_id'], ['signer.signer_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_signer_key_history_signer_id'), 'signer_key_history', ['signer_id'], unique=False)
    op.create_table('witness',
    sa.Column('witness_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('witness_value_hex', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['accumulator_element.element_id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['accumulator_state.state_id'], ),
    sa.PrimaryKeyConstraint('witness_id')
    )
    op.create_index(op.f('ix_witness_element_id'), 'witness', ['element_id'], unique=False)
    op.create_index(op.f('ix_witness_state_id'), 'witness', ['state_id'], unique=False)
    # ### end Alembic commands ###

    # Seed das tabelas de lookup (dados de referência exigidos pelo schema:
    # document_signer.status_id é FK para signer_status).
    document_status = sa.table(
        'document_status',
        sa.column('status_id', sa.Integer),
        sa.column('name', sa.String),
    )
    op.bulk_insert(document_status, [
        {'status_id': 1, 'name': 'Criado'},
        {'status_id': 2, 'name': 'Em andamento'},
        {'status_id': 3, 'name': 'Assinado'},
        {'status_id': 4, 'name': 'Cancelado'},
    ])

    signer_status = sa.table(
        'signer_status',
        sa.column('status_id', sa.Integer),
        sa.column('name', sa.String),
    )
    op.bulk_insert(signer_status, [
        {'status_id': 1, 'name': 'PENDING'},
        {'status_id': 2, 'name': 'IDENTITY_VERIFIED'},
        {'status_id': 3, 'name': 'IDENTITY_FAILED'},
        {'status_id': 4, 'name': 'SIGNED'},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_witness_state_id'), table_name='witness')
    op.drop_index(op.f('ix_witness_element_id'), table_name='witness')
    op.drop_table('witness')
    op.drop_index(op.f('ix_signer_key_history_signer_id'), table_name='signer_key_history')
    op.drop_table('signer_key_history')
    op.drop_table('document_signer')
    op.drop_table('accumulator_element_state')
    op.drop_index(op.f('ix_signer_national_id'), table_name='signer')
    op.drop_table('signer')
    op.drop_table('reset_password_tokens')
    op.drop_table('public_accumulator_registry')
    op.drop_table('notification_tokens')
    op.drop_table('company')
    op.drop_table('accumulator_element')
    op.drop_table('user_account')
    op.drop_table('signer_status')
    op.drop_table('otp_codes')
    op.drop_table('identity_document')
    op.drop_table('document_status')
    op.drop_table('document')
    op.drop_table('digital_signature')
    op.drop_table('auth_log')
    op.drop_table('audit_log')
    op.drop_table('accumulator_state')
    # ### end Alembic commands ###
